MONGODB_HOST: mongodb- {{ env }}.bpotla.com
REDIS_HOST:  redis-{{ env }}.bpotla.com
CATALOGUE_HOST: catalogue-{{ env }}.bpotla.com
CART_HOST: cart.daws86s.fun
USER_HOST: user.daws86s.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.bpotla.com
MYSQL_HOST: mysql-{{ env }}.bpotla.com
SHIPPING_HOST: shipping.daws86s.fun
PAYMENT_HOST: payment.daws86s.fun