MONGODB_HOST: mongodb-{{ env }}.bpotla.com
REDIS_HOST:  redis-{{ env }}.bpotla.com
CATALOGUE_HOST: catalogue-backendalb-{{ env }}.bpotla.com
CART_HOST: cart.backendalb-{{ env }}.bpotla.com
USER_HOST: user.backendalb-{{ env }}.bpotla.com
RABBITMQ_HOST: rabbitmq-{{ env }}.bpotla.com
MYSQL_HOST: mysql-{{ env }}.bpotla.com
SHIPPING_HOST: shipping.backendalb-{{ env }}.bpotla.com
PAYMENT_HOST: payment.backendalb-{{ env }}.bpotla.com